# ------------------------------------------------------------ #
# Configuration file for CustomCommands
# ------------------------------------------------------------ #

# ------------------------------------------------------------ #
# Messages
# ------------------------------------------------------------ #

msg:
  error-permission: '&4CustomCommands >> &cYou don''t have the permission to do that !'
#	FRA: '&4CustomCommands >> &cTu n''as pas la permission de faire cela !'
  error-number: '&4CustomCommands >> &cError : ''{error}'' is not a valid number !'
#	FRA: '&4CustomCommands >> &cErreur : ''{error}'' n''est pas un nombre valide !'
  error-length: '&4CustomCommands >> &cError : ''{error}'' exceed the allowed size !'
#	FRA: '&4CustomCommands >> &cErreur : ''{error}'' dépasse la taille maximale !'
  error-target: '&4CustomCommands >> &cPlayer ''{player}'' could not be found.'
#	FRA: '&4CustomCommands >> &cLe joueur ''{player}'' n''a pas pu être trouvé.'
  error-usage: '&4CustomCommands >> &cThat''s not how you''re supposed to use the command ! Usage : {usage}'
#	FRA: '&4CustomCommands >> &cCe n''est pas la manière dont tu es supposé utiliser la commande ! Usage : {usage}'
