name: CustomCommands
description: The easiest, and most feature packed Custom Commands plugin!
author: PYRRH4
website: https://www.spigotmc.org/resources/authors/pyrrh4.70459/
main: be.pyrrh4.customcommands.CustomCommands
version: 2.1.0
depend: [PyrCore]
commands:
  customcommands:
    description: Custom commands
    aliases: [ccmd,cc,customcmd,ccmds,customcmds]
permissions:
  customcommands.admin:
    default: op
